# Generated by Django 5.0.7 on 2024-07-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_image',
            field=models.ImageField(upload_to='recipie'),
        ),
    ]
